[project]
name = "nowplaying"
version = "0.1.0"
description = "Now playing overlays for OBS"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.8",
    "django-environ>=0.12.0",
    "psycopg2-binary>=2.9.11",
]
